title: Duke of Lancaster Regiment Field Training Manual
logo: /_static/400px-The_Duke_of_Lancaster's_Regiment_Cap_Badge.png
description: Field Training Manual for the Duke of Lancaster Regiment Arma 3 Unit
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
