title: Duke of Lancaster Regiment Field Training Manual
logo: /img/logo.png
description: Field Training Manual for the Duke of Lancaster Regiment Arma 3 Unit
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
