title: Duke of Lancaster Regiment Field Training Manual
logo: img/logo.png
description: Field Training Manual for the Duke of Lancaster Regiment Arma 3 Unit
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl: docs.dlr-arma3.co.uk
